### ISSUE TITLE
An example of userbot.p12 file

### ISSUE THREAD

**Issue by opolyo01** [symphonyoss/symphony-java-sample-bots#1]
Do you have an example of userbot.p12 file? How do you generate those entries?

RECEIVER_USER_EMAIL=receiver@mycompany.com
BOT_USER_EMAIL=userbot@mycompany.com
BOT_CERT_PATH=./certs/userbot.p12
BOT_CERT_PASSWORD=changeit
TRUSTSTORE_PATH=./certs/server.truststore
TRUSTSTORE_PASSWORD=changeit

**Comment by pmonks** [comment]
The `userbot.p12` file is a Symphony "service account" certificate.  These are typically generated by an administrator of your pod, and are specific to the pod that generated them (so providing an example wouldn't necessarily be useful, nor would it be secure).

The `server.truststore` file is a standard Java truststore file - [here's some documentation describing how to create one](https://www.cloudera.com/documentation/enterprise/5-6-x/topics/cm_sg_create_key_trust.html).  This is something that could be provided as an example.

**Comment by maoo** [comment]
Here's some examples and scripts I've collected to generate, store and distribute certificates - https://github.com/symphonyoss/certificate-toolbox ; hope it helps.

Marking this as done, feel free to reopen in case you have more questions about it.
