### ISSUE TITLE
Missing PresenceListener on Symphony Java Client

### ISSUE THREAD

**Issue by maoo** [symphonyoss/symphony-java-sample-bots#15]
Several tests are failing against the symphony-java-client version 1.0.2-SNAPSHOT:

```
[ERROR] /Users/m/w/projects/symphony-java-sample-bots/src/main/java/org/symphonyoss/examples/presenceservice/SymUserCache.java:[34,39] cannot find symbol
[ERROR]   symbol:   class PresenceListener
[ERROR]   location: package org.symphonyoss.client.services
```

The following examples have been commented out to avoid the build to fail, therefore they need to be reimplemented according to the changes applied to the Symphony Java Client:

- src/main/java/org/symphonyoss/examples/hashtagbot/HashtagBot.java
- src/main/java/org/symphonyoss/examples/presenceservice/PresenceServiceExample.java
- src/main/java/org/symphonyoss/examples/presenceservice/SymUserCache.java
- src/main/java/org/symphonyoss/examples/setpresence/SetPresenceExample.java

**Comment by maoo** [comment]
@ftbb - what is the listener to use instead of `PresenceListener`?

**Comment by ftbb** [comment]
I must modify the example, because we have retired the PresenceService in 1.0.2-SNAPSHOT.



ftbb
