### ISSUE TITLE
Dependency not resolvable

### ISSUE THREAD

**Issue by chongzhe** [symphonyoss/symphony-java-sample-bots#5]
Following the instruction on README.md to build the repo

git clone https://github.com/symphonyoss/symphony-java-sample-bots.git
cd symphony-java-sample-bots
mvn clean package

Get the following error:

[ERROR] Failed to execute goal on project symphony-java-sample-bots: Could not resolve dependencies for project org.symphonyoss:symphony-java-sample-bots:jar:0.9.0-SNAPSHOT: Could not find artifact org.symphonyoss.symphony:symphony-client:jar:1.0.0-SNAPSHOT in sonatype-oss-public (https://oss.sonatype.org/content/groups/public/) -> [Help 1]

**Comment by maoo** [comment]
Thanks @chongzhe ! The issue is fixed on `dev` branch

**Comment by chongzhe** [comment]
@maoo Thanks for the quick fix:)

I can build the repo on the dev branch now, is the master branch going to be fixed as well once sonatype can host more than one version of the jar as described in https://github.com/symphonyoss/symphony-java-sample-bots/commit/4b01d9906fbf27bcde0cceaa6c7194f511c85dd9 ?

**Comment by maoo** [comment]
No need to wait for sonatype, just merged changes on master!

Thank you for raising the issue! Feel free to close it if you don't have any other build problem.

**Comment by chongzhe** [comment]
Verified that master branch builds fine now, closing the issue.

Thanks again @maoo

**Comment by chongzhe** [comment]
Sorry for re-opening this issue, I had similar problem in the following repos too:

https://github.com/symphonyoss/App-Integrations-Core
https://github.com/symphonyoss/App-Integrations-Commons

I thought I might reuse this issue since they are likely due to the same cause. Here is one of the error message:

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.symphonyoss:integration:[unknown-version]: Could not transfer artifact org.symphonyoss:integration-parent:pom:0.10.0-SNAPSHOT from/to snapshots (https://repo.symphony.com/artifactory/libs-snapshot): Not authorized , ReasonPhrase:Unauthorized. and 'parent.relativePath' points at wrong local POM @ org.symphonyoss:integration:[unknown-version], /workspace/pom.xml, line 7, column 13

**Comment by maoo** [comment]
The projects you mention are part of the Symphony Integrations, you can read more on http://blog.symphony.foundation/symphony-integrations-open-source-status-roadmap

Right now the projects don't build yet, but they will by the end of this week (the team is working on this issue as we type); I'll make sure to send you an update here as soon as you can run a successful build.

If you have more issues related with Symphony Integrations, it's better to use https://github.com/symphonyoss/App-Integrations-Core/issues , so that the dev team can answer you directly.

Thanks!

**Comment by chongzhe** [comment]
Sounds good! I will check again at the end of the week, thank you so much!
